version: '3.0'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 2000:80
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - 4000:4000
    working_dir: /usr/src/app
    env_file:
      - ./.env.backend
    command: npm start
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABSE: "smartplan_db"
    ports:
      - 27017:27017
    volumes:
      - './data:/data/db'
