version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 2000:80
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - 4000:4000
    working_dir: /usr/src/app
    command: npm start
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "supla_db"
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
